GET http://localhost:3001/api/blogs/

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "Z Kuşağı Jargonu",
    "author": "Ali",
    "url": "https://www.alidindar.tr/z-kusagi-jargonu-2025/",
    "likes": 3
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "Z Kuşağı Jargonu",
    "url": "hello"
}

###
DELETE http://localhost:3001/api/blogs/69528d3631697c271e823ca6


